### ISSUE TITLE
3.0.0 does not match the docs

### ISSUE THREAD

**Issue by mensfeld** [librariesio/spdx#70]
While reviewing the 3.0.0 release: https://my.diffend.io/gems/spdx/2.0.12/3.0.0#d2h-088930-307 I noticed that the find method has been removed but is still present in the master docs. Is that intentional? Where can I find the upgrade notes for this release?

Also, would you mind providing some insight on why you've removed the fuzzy matching methods? It worked remarkably well.

**Comment by mellisio** [comment]
Sorry about that! The docs have been updated. We decided to remove the fuzzy matching methods from the 3.* series because we had some issues that led us to conclude that doing license matching with a levenshtein distance wasn't providing us with a sufficient accuracy level. Some examples:

`Spdx.find("MirOS License (MirOS)")
=> #<Spdx::License:0x000055f6b9894cd8 @id="MIT", @name="MIT License", @osi_approved=true>
`
`Spdx.find("BSD")
=> #<Spdx::License:0x000055f6b98bdb60
 @id="BSD-3-Clause",
 @name="BSD 3-Clause \"New\" or \"Revised\" License",
 @osi_approved=true>
`
`Spdx.find("MIT or GPLv3")
=> #<SpdxLicenses::License:0x0000564f1a7cb7c0 @id="MIT", @name="MIT License", @osi_approved=true>`
` Spdx.find("GWT Terms")
=> #<SpdxLicenses::License:0x0000564f1a6f7e48
 @id="Unicode-TOU",
 @name="Unicode Terms of Use",
 @osi_approved=false>
`

**Comment by mensfeld** [comment]
@mellisio thank you for the update. Wouldn't it be solved if there would be a probability included in the result? Then matches below a certain threshold could be rejected.
